#!/usr/bin/env sh

WIFI_NAME=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk -F': ' '/ SSID/{print $2}')

ON_ICON=""
OFF_ICON'⨉'
TAIL="#[fg=colour237] "

[ -n "$WIFI_NAME" ] && printf "%s" "$ON_ICON  $WIFI_NAME$TAIL" || printf "#[fg=red]%s" "$OFF_ICON$TAIL"