#!/bin/bash
GITHUB_STATUS=$(curl -s https://kctbh9vrtdwd.statuspage.io/api/v2/status.json | jq -r '.status')

INDICATIOR="#[fg=colour237]⦁"

case $GITHUB_STATUS in
ma*)
  STATUS="#[fg=red]   $INDICATOR "
  ;;
mi*)
  STATUS="#[fg=yellow]   $INDICATIOR "
  ;;
*)
  STATUS=""
  ;;
esac

printf "%s" "$STATUS"