#!/bin/bash

if [ -e "$HOME/Projects/_Repo/zsh-dotfiles" ]; then
  echo "Pulling repository..."
  git -C $HOME/Projects/_Repo/zsh-dotfiles pull
else
  echo "Cloning repository..."
  git clone https://github.com/AhmedAbdulrahman/zsh-dotfiles $HOME/Projects/_Repo/zsh-dotfiles
fi
echo

# echo "Switching shell to zsh..."
# if [ "$SHELL" != "/bin/zsh" ]; then
#   if [ "$(uname)" = "Darwin" ]; then
#     #chsh -s /usr/local/bin/fish
#     chsh -s $(which zsh)
#   else
#     sudo chsh --shell /bin/zsh "$(whoami)"
#   fi
# fi
# echo

echo "Symlinking config files..."
stow . --dir $HOME/Projects/_Repo/zsh-dotfiles --target $HOME
echo

# echo "Make VSCode as mergetool..."
# if which code >/dev/null 2>&1; then
# 	git config --global merge.tool vscode
# 	git config --global mergetool.vscode.cmd "code --wait $MERGED"
# fi
# echo