-- Skip setting defualt mappings.
vim.g.lightspeed_no_default_keymaps = true

require('lightspeed').setup({
  ignore_case = true,
  repeat_ft_with_target_char = true,
  --jump_to_first_match = true,
  exit_after_idle_msecs = { labeled = 1500, unlabeled = 1000 },
  safe_labels = {
    's',
    'f',
    'n',
    'u',
    't',
    'b',
    'g',
    'F',
    'L',
    'N',
    'H',
    'G',
    'M',
    'U',
    'T',
    'Z',
  },
  labels = {
    's',
    'f',
    'n',
    'g',
    'h',
    'v',
    'b',
    'w',
    'y',
    'd',
    'q',
    'z',
    'c',
    'x',
    't',
    'u',
    'r',
    'i',
    'a',
    'o',
    'e',
  },
  match_only_the_start_of_same_char_seqs = true,
  limit_ft_matches = 5,
  --x_mode_prefix_key = "<c-x>",
  substitute_chars = { ['\r'] = '¬' },
  instant_repeat_fwd_key = nil,
  instant_repeat_bwd_key = nil,
  -- If no values are given, these will be set at runtime,
  -- based on `jump_to_first_match`.
  --   labels = nil,
  cycle_group_fwd_key = nil,
  cycle_group_bwd_key = nil,
  -- This can get _really_ slow if the window has a lot of content,
  -- turn it on only if your machine can always cope with it.
  jump_to_unique_chars = true,
})
