#!/usr/bin/env zsh
#!/usr/bin/env zsh

# --- Moving around ---
alias ..="cd .."
alias ...="cd ../.."
alias cd..="cd .."
alias oo='open .'

# --- Shortcust ---
alias dot='cd ~/dotfiles'
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias p="cd ~/Projects"

# --- Copy & Move ---
# `rm` and `mv` are so dangerous, they must always ask for confirmation.
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

# --- Permission ---
alias chmox='chmod -x'

# Exa
alias l='exa -1a'                 # Lists in one column, hidden files.
alias ll='exa -l'                 # Lists human readable sizes.
alias lr='ll -R'                  # Lists human readable sizes, recursively.
alias la='ll -a'                  # Lists human readable sizes, hidden files.
alias lm='la | "$PAGER"'          # Lists human readable sizes, hidden files through pager.
alias lx='ll --sort=Extension'    # Lists sorted by extension (GNU only).
alias lk='ll --sort=size -r'      # Lists sorted by size, largest last.
alias lt='ll --sort=modified -r'  # Lists sorted by date, most recent last.
alias lc='lt -m'                  # Lists sorted by date, most recent last, shows change time.
alias lu='lt -u'                  # Lists sorted by date, most recent last, shows access time.
alias sl='ls'                     # I often screw this up.

# Npm
alias npm-update="npx npm-check -u"
alias ni="npm install"
alias nrs="npm run start -s --"
alias nrb="npm run build -s --"
alias nrd="npm run dev -s --"
alias nrt="npm run test -s --"
alias nrtw="npm run test:watch -s --"
alias nrv="npm run validate -s --"
alias rmn="rm -rf node_modules"
alias flush-npm="rm -rf node_modules && npm i && echo NPM is done"
alias nicache="npm install --prefer-offline"

# Yarn
alias yar="yarn run";
alias yas="yarn run start -s --";
alias yab="yarn run build -s --";
alias yat="yarn run test -s --";
alias yav="yarn run validate -s --";
alias yoff="yarn add --offline";
alias ypm="echo \"Installing deps without lockfile and ignoring engines\" && yarn install --no-lockfile --ignore-engines"

# --- Git ---
alias git=hub
alias g='git'
alias add="git add"
alias gb="git branch"
alias gba="git branch -a"
alias commit='git commit -m'
alias amend="git commit --amend"
alias gco="git checkout"
alias gcb='gco -b'
alias master="git checkout master"
alias develop="git checkout develop"
alias status="git status"
alias push="git push"
alias pushu='git push upstream'
alias pull='git pull'
alias pullu='git pull upstream'
alias remote='git remote'
alias stash='git stash'
alias save='git stash save -u'
alias gsp='git stash pop'

alias logf='git log --date-order --all --graph --format="%C(green)%h%Creset %C(yellow)%an%Creset %C(blue bold)%ar%Creset %C(red bold)%d%Creset%s"'
alias logs='git log --date-order --all --graph --name-status --format="%C(green)%h%Creset %C(yellow)%an%Creset %C(blue bold)%ar%Creset %C(red bold)%d%Creset%s"'
alias loga='git log --graph --decorate --pretty=oneline --abbrev-commit --all'
alias logd='git log --graph --decorate --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset --abbrev-commit --date=relative --all"'
# Undo commit and unstage all files
alias undo='git reset HEAD~'
# Undo commit and keep all files staged
alias undosoft='git reset --soft HEAD~'
# Undo the commit and completely remove all changes
alias undohard='git reset --hard HEAD~'
alias undopush='git push -f origin HEAD^:master'
alias unstage='git reset --'

# --- Docker ---
alias dps='docker ps'
alias dpsa='dps -a'
alias drun='docker run'
alias drm='docker rm'
alias drmi='docker rmi'
alias da='docker attach'
alias dim='docker images'
alias dp='docker pull'
alias dstop='docker stop'
alias dstart='docker start'
alias dexec='docker exec'
alias ds='docker service'
alias dm='docker-machine'
alias k='kubectl'
# alias dacker="docker-compose build && docker-compose up"
# alias dacker-down="docker-compose down && docker-compose rm"
# alias dacker-stop="docker-compose kill"
# alias dacker-clean="docker volume rm $(docker volume ls -qf dangling=true) && docker rmi $(docker images -f dangling=true -q)"

# --- Timewarrior ---
alias tw='timew'
alias "tw sum"='timew summary'
alias "tws"='timew start'
alias "twp"='timew stop'
alias "twt"='timew stop'

# Resource Usage
alias df='df -kh'
alias du='du -kh'
alias diskspace='du -h -d 2'
#alias diskspace='du -s | sort -n -r |more'

# Terminal
alias "?"="pwd"
alias c="clear "
alias KABOOM="yarn global upgrade --latest;brew update; brew upgrade; brew cleanup -s; brew doctor"
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes;sudo rm -rfv ~/.Trash"
alias fs="stat -f '%z bytes'"
alias flushdns="sudo killall -HUP mDNSResponder"
if (( $+commands[jq] )) then;
  alias formatJSON='jq .'
else
  alias formatJSON='python -m json.tool'
fi

# --- IP Addresses ---
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias localip="ipconfig getifaddr en1"
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"
alias myip="ifconfig | grep 'inet ' | grep -v 127.0.0.1 | awk '{print \$2}'"
alias lsof-tcp='lsof -iTCP'
alias lsof-tcp-listen='lsof -iTCP -sTCP:LISTEN -P'
alias hosts='sudo $EDITOR /etc/hosts'

# --- Tmux ---
# Conditional aliases
# https://gist.github.com/sos4nt/3187620#gistcomment-1452131
[[ $TERM == *"tmux"* ]] && alias :sp='tmux split-window'
[[ $TERM == *"tmux"* ]] && alias :vs='tmux split-window -h'
[[ $TERM == *"tmux"* ]] && alias ssh="TERM=xterm-256color ssh"
[[ $TERM == *"tmux"* ]] && alias vagrant="TERM=xterm-256color vagrant"
[[ $TERM == *"tmux"* ]] && alias brew="TERM=xterm-256color brew"
alias tmux='tmux -2'
alias mks='tmux kill-session -t'
alias mkS='tmux kill-server'
alias tn='tmux new-session -s'
alias tl='tmux list-sessions'

# --- Shell ---
alias vv='vim $(fzf)'
alias vi=vim
alias zcfg="vim ~/.zshrc"
alias refresh='source ~/.zshrc; echo "Reloaded .zshrc."'
alias less='less -r'
alias tf='tail -f'
alias cl='clear'
# Reload the shell (i.e. invoke as a login shell)
alias reload="exec ${SHELL} -l"
# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# --- Applications ---
alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'
alias ios='open -a /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone\ Simulator.app'

if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
	export LS_COLORS='no=00:fi=00:di=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
else # macOS `ls`
	colorflag="-G"
	export LSCOLORS='BxBxhxDxfxhxhxhxhxcxcx'
fi

# --- System ---
alias bye='sudo shutdown -h now'
alias update='sudo apt-get update && sudo apt-get upgrade'
alias upgrade='sudo apt-get upgrade'
alias clean='sudo apt-get autoclean && sudo apt-get autoremove'
# System monitoring
alias top-cpu='top -n 10 -o cpu -O time -stats pid,command,cpu,cpu_me,time,threads,ports'
# Trim new lines and copy to clipboard
alias trimcopy="tr -d '\n' | pbcopy"
# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"
# Empty the Trash on all mounted volumes and the main HDD.
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"
# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
# Kill all the tabs in Chrome to free up memory
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"
# Lock the screen (when going AFK = Away From Keyboard)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# --- Cleaners ---
alias rm_modules="find . -name "node_modules" -type d -prune -exec rm -rf '{}' +"
# Recursively delete `.DS_Store` files
alias cleanup_dsstore="find . -name '*.DS_Store' -type f -ls -delete"

# One of @janmoesen’s ProTip™s HTTP requests
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
	alias "${method}"="lwp-request -m '${method}'"
done

# File size
alias fs="stat -f \"%z bytes\""

alias diskspace_report="df -P -kHl"
alias free_diskspace_report="diskspace_report"

# --- LiveStream ---
# Get Prepared for LiveStream
alias tutMode='defaults write com.apple.dock autohide -bool true;
							 killall Dock;
							 defaults write com.apple.menuextra.clock IsAnalog -bool true;
							 killall SystemUIServer;
							 rm -rf ~/.Trash/*;'

# Set everything back to Normal (Regular Mode)
alias regMode='defaults write com.apple.dock autohide -bool false
							killall Dock;
							defaults write com.apple.menuextra.clock IsAnalog -bool false;
							killall SystemUIServer;'