#!/usr/bin/env zsh

# Put this line on top to make keybinds work
bindkey -e

# CTRL+R search
# bindkey -v
# bindkey '^R' history-incremental-search-backward

# byPass Ctrl+S through iTerm for VIM
stty -ixon

# Change cursor shape based on vim mode
function zle-keymap-select zle-line-init
{
   # change cursor shape in iTerm2
   case $KEYMAP in
       vicmd)      print -n -- "\E]50;CursorShape=0\C-G";;  # block cursor
       viins|main) print -n -- "\E]50;CursorShape=1\C-G";;  # line cursor
   esac

   zle reset-prompt
   zle -R
}

function zle-line-finish
{
   print -n -- "\E]50;CursorShape=1\C-G"  # block cursor
}

zle -N zle-line-init
zle -N zle-line-finish
zle -N zle-keymap-select

# - Exports
export ZSH=$HOME/.oh-my-zsh
# ZSH_THEME="jovial"

# --- Source
source ~/.zsh_env

source ~/.fzf.zsh      
source ~/.zsh_fzf_extra

source ~/.zsh_plug
source ~/.zsh_keybinds
source ~/.zsh_misc
source ~/.zsh_aliases
source ~/.zsh_functions

source ~/.zsh_theme 2>/dev/null

# source $ZSH/oh-my-zsh.sh

(( $+commands[thefuck] )) && source <(thefuck --alias 2>/dev/null)
# (( $+commands[kubectl] )) && source <(kubectl completion zsh)
(( $+commands[pyenv]   )) && source <(pyenv init -)

return 0