#!/usr/bin/env zsh

# byPass Ctrl+S through iTerm for VIM
stty -ixon

# - Exports
export ZSH=$HOME/.oh-my-zsh
# ZSH_THEME="jovial"

# --- Source
source ~/.zsh_env

source ~/.fzf.zsh
source ~/.zsh_fzf_extra

source ~/.zsh_plug
source ~/.zsh_misc
source ~/.zsh_keybinds
source ~/.zsh_aliases
source ~/.zsh_functions

source ~/.zsh_theme 2>/dev/null

# source $ZSH/oh-my-zsh.sh

(( $+commands[thefuck] )) && source <(thefuck --alias 2>/dev/null)
# (( $+commands[kubectl] )) && source <(kubectl completion zsh)
(( $+commands[pyenv]   )) && source <(pyenv init -)

return 0
