print('==================================================')
require "application.application"
require "battery.battery"
require "clipboard.clipboard"
require "health.health"
require "hotkey.hotkey"
require "ime.ime"
require "reload.reload"
require "speaker.speaker"
require "system.system"
require "usb.usb"
require "volume.volume"
require "window.window"