-- luacheck: globals hs, no unused

--- Keep monitors on
local ampOnIcon = [[ASCII:
.....1a..........AC..........E
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3..........t..q....
5..........c..........s.......
......6..................q....
......................s..t....
.....5c.......................
]]

local ampOffIcon = [[ASCII:
.....1a.....x....AC.y.......zE
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3..........t..q....
5..........c..........s.......
......6..................q....
......................s..t....
...x.5c....y.......z..........
]]

-- caffeine replacement
local awakeMenu = hs.menubar.new()

local function setIcon(state)
  awakeMenu:setIcon(state and ampOnIcon or ampOffIcon)
end

local function caffeineClicked()
  setIcon(hs.caffeinate.toggle('displayIdle'))
end

if awakeMenu then
  awakeMenu:setClickCallback(caffeineClicked)
  setIcon(hs.caffeinate.toggle('displayIdle'))
end
